"""Utilities for generating MonsterList.xml from monsters list."""
from __future__ import annotations

import xml.etree.ElementTree as ET
import io
import os
import shutil
import datetime
import sys
from typing import List

MONSTER_FIELDS_NAMES = [
    "Index","Level","Life","Mana","DamageMin","DamageMax","Defense","MagicDefense",
    "AttackRate","DefenseRate","MoveRange","AttackType","AttackRange","ViewRange",
    "MoveSpeed","AttackSpeed","RegenTime","Attribute","ItemRate","MoneyRate",
    "MaxItemLevel","MonsterSkill","IceRes","PoisonRes","LightRes","FireRes","Name"
]


def now_stamp() -> str:
    return datetime.datetime.now().strftime("%Y%m%d_%H%M%S")


def backup_file(path: str) -> None:
    if not os.path.isfile(path):
        return
    # backups folder inside the app directory (module dir)
    if getattr(sys, 'frozen', False):
        app_dir = os.path.dirname(sys.executable)
    else:
        app_dir = os.path.dirname(os.path.abspath(__file__))
    backups_dir = os.path.join(app_dir, "backups")
    os.makedirs(backups_dir, exist_ok=True)
    base = os.path.basename(path)
    name, ext = os.path.splitext(base)
    bak_name = f"{name}_{now_stamp()}{ext}"
    bak_path = os.path.join(backups_dir, bak_name)
    shutil.copy2(path, bak_path)


def indent_xml(elem: ET.Element, level: int = 0) -> None:
    i = "\n" + ("  " * level)
    if len(elem):
        if not elem.text or not elem.text.strip():
            elem.text = i + "  "
        for child in elem:
            indent_xml(child, level + 1)
        if not elem.tail or not elem.tail.strip():
            elem.tail = i
    else:
        if level and (not elem.tail or not elem.tail.strip()):
            elem.tail = i


def regenerate_monster_list_xml(path: str, monsters: List[dict]) -> None:
    root = ET.Element("MonsterList")
    for m in sorted(monsters, key=lambda x: x["Index"]):
        attrs = {}
        for name in MONSTER_FIELDS_NAMES:
            if name == "Name":
                attrs["Name"] = str(m.get("Name", ""))
            else:
                attrs[name] = str(m.get(name, 0))
        ET.SubElement(root, "Monster", attrib=attrs)
    indent_xml(root)
    tree = ET.ElementTree(root)
    backup_file(path)
    with open(path, "wb") as f:
        f.write(b'<?xml version="1.0" encoding="utf-8"?>\n')
        f.write(b'<!-- Generated by MU Monster Editor -->\n')
        tree.write(f, encoding="utf-8", xml_declaration=False)


def render_monsterlist_string(monsters: List[dict]) -> str:
    root = ET.Element("MonsterList")
    for m in sorted(monsters, key=lambda x: x["Index"]):
        attrs = {}
        for name in MONSTER_FIELDS_NAMES:
            if name == "Name":
                attrs["Name"] = str(m.get("Name", ""))
            else:
                attrs[name] = str(m.get(name, 0))
        ET.SubElement(root, "Monster", attrib=attrs)
    indent_xml(root)
    tree = ET.ElementTree(root)
    bio = io.BytesIO()
    bio.write(b'<?xml version="1.0" encoding="utf-8"?>\n')
    bio.write(b'<!-- Generated by MU Monster Editor (preview) -->\n')
    tree.write(bio, encoding="utf-8", xml_declaration=False)
    return bio.getvalue().decode("utf-8")
