"""I/O utilities for MonsterSpawn.xml parsing and saving."""
from __future__ import annotations

import xml.etree.ElementTree as ET
import os
import shutil
import datetime
import sys
from typing import Optional


def now_stamp() -> str:
    return datetime.datetime.now().strftime("%Y%m%d_%H%M%S")


def backup_file(path: str) -> None:
    if not os.path.isfile(path):
        return
    if getattr(sys, 'frozen', False):
        app_dir = os.path.dirname(sys.executable)
    else:
        app_dir = os.path.dirname(os.path.abspath(__file__))
    backups_dir = os.path.join(app_dir, "backups")
    os.makedirs(backups_dir, exist_ok=True)
    base = os.path.basename(path)
    name, ext = os.path.splitext(base)
    bak_name = f"{name}_{now_stamp()}{ext}"
    bak_path = os.path.join(backups_dir, bak_name)
    shutil.copy2(path, bak_path)


def parse_monster_spawn_xml(path: str) -> ET.ElementTree:
    return ET.parse(path)


def indent_xml(elem: ET.Element, level: int = 0) -> None:
    i = "\n" + ("  " * level)
    if len(elem):
        if not elem.text or not elem.text.strip():
            elem.text = i + "  "
        for child in elem:
            indent_xml(child, level + 1)
        if not elem.tail or not elem.tail.strip():
            elem.tail = i
    else:
        if level and (not elem.tail or not elem.tail.strip()):
            elem.tail = i


def save_monster_spawn_xml(path: str, tree: ET.ElementTree) -> None:
    root = tree.getroot()
    indent_xml(root)
    backup_file(path)
    with open(path, "wb") as f:
        f.write(b'<?xml version="1.0" encoding="utf-8"?>\n')
        f.write(b'<!-- Generated by MU Monster Editor -->\n')
        tree.write(f, encoding="utf-8", xml_declaration=False)
